In [1]:
import numpy as np
import pandas as pd
import re
import nltk

In [2]:
pitch_file = 'shark_tank_pitch_detail.csv'

load2 = pd.read_csv(pitch_file)
load2.head()

Season_Epi_code  Pitched_Business_Identifier  \
0              101             Ava the Elephant   
1              101  College Foxes Packing Boxes   
2              101                    Ionic Ear   
3              101        Mr. Tod's Pie Factory   
4              101                      Wispots   

                               Pitched_Business_Desc  Deal_Status Deal_Shark  
0   (Emmy the Elephant during show, trademarked a...            1         BC  
1  a packing and organizing service based on an a...            0        NaN  
2  an implantable Bluetooth device requiring surg...            0        NaN  
3                                     a pie company             1      BC+DJ  
4  an electronic hand-held device for waiting roo...            0        NaN

In [3]:
def data_cleaning(corpus):
    letters_only = re.sub("[^a-zA-Z]", " ", corpus) 
    words = letters_only.lower().split()                            
    return( " ".join( words ))     

In [4]:
from nltk.corpus import stopwords

In [6]:
addedwords = ('use','line','allow','make','offer','provide','products','design','made','similar','like','play','creates','created','unique')

stop = stopwords.words('english')+list(addedwords)

load2['Pitched_Business_Desc'] = load2['Pitched_Business_Desc'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

In [7]:
load2['Pitched_Business_Desc'] = load2['Pitched_Business_Desc'].apply(lambda x:data_cleaning(x))
load2 = load2[['Deal_Status','Pitched_Business_Desc']]
for i in range(5):
    print(load2['Pitched_Business_Desc'][i])

emmy elephant show trademarked ava after plastic elephant shaped device helps parents give small children oral medicine emmy elephant show trademarked ava after plastic elephant shaped device lets parents easily give small children oral medicine
packing organizing service based already successful business called college hunks hauling junk spinoff professional packing organizing service based already successful junk removal moving business called college hunks hauling junk
implantable bluetooth device requiring surgery insert device user s head implantable bluetooth device requiring surgery head
pie company
electronic hand held device waiting rooms electronic hand held device waiting rooms


In [12]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(load2,test_size=0.2)

In [13]:
train_corpus = []
test_corpus = []
for each in train['Pitched_Business_Desc']:
    train_corpus.append(each)
for each in test['Pitched_Business_Desc']:
    test_corpus.append(each)
## Start creating them
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer(ngram_range=(2,2))
train_features = v.fit_transform(train_corpus)
test_features=v.transform(test_corpus)

In [14]:
print(train_features.shape)
print(test_features.shape)

(564, 8522)
(142, 8522)


In [15]:
# Import ML models from sklearn
from sklearn.linear_model import LogisticRegression # Regression classifier
from sklearn.tree import DecisionTreeClassifier # Decision Tree classifier
from sklearn import svm # Support Vector Machine
from sklearn.linear_model import SGDClassifier # Stochastic Gradient Descent Classifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier # Random Forest and Gradient Boosting Classifier
from sklearn.naive_bayes import MultinomialNB # Naive Bayes Classifier 
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix # Some metrics to check the performance of the models

In [16]:
#these are tunable to achieve max accuracy


Classifiers = {'LR':LogisticRegression(random_state=10,C=5,max_iter=200),
               'DTC':DecisionTreeClassifier(random_state=10,min_samples_leaf=2),
               'RF':RandomForestClassifier(random_state=10,n_estimators=100,n_jobs=-1),
               'GBC':GradientBoostingClassifier(random_state=10,n_estimators=400,learning_rate=0.2),
               'SGD':SGDClassifier(loss="hinge", penalty="l2"),
               'SVM':svm.SVC(kernel='linear', C=0.1),
               'NB':MultinomialNB(alpha=.05)}

In [17]:
#Pipeline to reuse the code
def ML_Pipeline(clf_name):
    clf = Classifiers[clf_name]
    fit = clf.fit(train_features,train['Deal_Status'])
    pred = clf.predict(test_features)
    Accuracy = accuracy_score(test['Deal_Status'],pred)
    Confusion_matrix = confusion_matrix(test['Deal_Status'],pred)
    print('==='*20)
    print('Accuracy = '+str(Accuracy))
    print('==='*20) 
    print(Confusion_matrix)

# # ML Code in Individual Blocks

In [18]:
ML_Pipeline('LR')

Accuracy = 0.528169014084507
[[ 8 55]
 [12 67]]


In [19]:
ML_Pipeline('DTC')

Accuracy = 0.5563380281690141
[[ 7 56]
 [ 7 72]]


In [20]:
ML_Pipeline('RF')

Accuracy = 0.5492957746478874
[[ 0 63]
 [ 1 78]]


In [21]:
ML_Pipeline('GBC')

Accuracy = 0.5492957746478874
[[ 3 60]
 [ 4 75]]


In [22]:
ML_Pipeline('NB')

Accuracy = 0.5352112676056338
[[15 48]
 [18 61]]


In [23]:
ML_Pipeline('SVM')

Accuracy = 0.5352112676056338
[[10 53]
 [13 66]]


In [24]:
ML_Pipeline('SGD')

Accuracy = 0.5
[[10 53]
 [18 61]]
