In [2]:
import numpy as np
import pandas as pd
import re
import nltk

In [3]:
data_file = 'shark_tank_data.csv'

load2 = pd.read_csv(data_file)


#Only keeping rows where ASK_Valuation is not null
load2 = load2[load2['ASK_Valuation'].notna()]

load2.head()

Season  Episode               Business Description  Deal  \
0         1        1       Ava the Elephant         NaN     1   
1         1        1  Mr. Tod's Pie Factory         NaN     1   
6         1        2         Classroom Jams         NaN     1   
263       5        1            Sweet Ballz         NaN     1   
264       5        1    Postcard on the Run         NaN     1   

               Category Entrepreneur Gender State ASK_Equity  ASK_Amount  ...  \
0       Health/Wellness              Female   NaN     15.00%     50000.0  ...   
1     Food and Beverage                Male    NJ     10.00%    460000.0  ...   
6    Children/Education                Male   NaN     10.00%    250000.0  ...   
263   Food and Beverage                Male   NaN     10.00%    250000.0  ...   
264       Software/Tech                Male   NaN      5.00%    300000.0  ...   

     Barbara Corcoran Mark Cuban  Lori Greiner  Robert Herjavec  Daymond John  \
0                   1          0             0                0             0   
1                   1          0             0                0             1   
6                   1          1             0                1             1   
263                 1          1             0                0             0   
264                 0          0             0                1             0   

    Kevin O'Leary  Guest  # Sharks   Investment/shark  \
0               0      0       1.0            50000.0   
1               0      0       2.0           230000.0   
6               1      0       5.0            50000.0   
263             0      0       2.0           125000.0   
264             0      0       1.0           300000.0   

                               Notes  
0                                NaN  
1                                NaN  
6    5% royalty for the entrepreneur  
263                              NaN  
264                              NaN  

[5 rows x 26 columns]

In [4]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(load2,test_size=0.25)

In [55]:
train_corpus = []
test_corpus = []
for each in train['ASK_Valuation']:
    train_corpus.append(each)
for each in test['ASK_Valuation']:
    test_corpus.append(each)
## Start creating them
from sklearn.feature_extraction import DictVectorizer
v = DictVectorizer()
train_features = np.array(train_corpus).reshape(-1,1)
test_features = np.array(test_corpus).reshape(-1,1)

In [28]:
print(train_features)
print(test_features)

[[ 3666667.]
 [16000000.]
 [ 1000000.]
 [  800000.]
 [ 3500000.]
 [  600000.]
 [ 6000000.]
 [ 3000000.]
 [ 8000000.]
 [ 1000000.]
 [ 1000000.]
 [ 4600000.]
 [  300000.]
 [ 1000000.]
 [ 5000000.]
 [ 5000000.]
 [ 4000000.]
 [ 1000000.]
 [ 4285714.]
 [ 5500000.]
 [  625000.]
 [ 1250000.]
 [10000000.]
 [ 1500000.]
 [ 3000000.]
 [10000000.]
 [  400000.]
 [ 2500000.]
 [ 3000000.]
 [ 3000000.]
 [  800000.]
 [ 4000000.]
 [  500000.]
 [ 3500000.]
 [ 1333333.]
 [  750000.]
 [ 4000000.]
 [14285714.]
 [ 2000000.]
 [ 3000000.]
 [12500000.]
 [  250000.]
 [ 8333333.]
 [13333333.]
 [ 2500000.]
 [  625000.]
 [  250000.]
 [ 2500000.]
 [ 4000000.]
 [  750000.]
 [  800000.]
 [ 4000000.]
 [ 2500000.]
 [ 1666667.]
 [ 2500000.]
 [10000000.]
 [ 5000000.]
 [ 2000000.]
 [ 2000000.]
 [  100000.]
 [ 4600000.]
 [ 1666667.]
 [ 5000000.]
 [ 1000000.]
 [ 1250000.]
 [ 1000000.]
 [ 2000000.]
 [ 1000000.]
 [ 4000000.]
 [  625000.]
 [ 2857143.]
 [ 1000000.]
 [ 4000000.]
 [ 4000000.]
 [  750000.]
 [  800000.]
 [ 2500000.]

In [43]:
# Import ML models from sklearn
from sklearn.linear_model import LogisticRegression # Regression classifier
from sklearn.tree import DecisionTreeClassifier # Decision Tree classifier
from sklearn import svm # Support Vector Machine
from sklearn.linear_model import SGDClassifier # Stochastic Gradient Descent Classifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier # Random Forest and Gradient Boosting Classifier
from sklearn.naive_bayes import MultinomialNB # Naive Bayes Classifier 
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix # Some metrics to check the performance of the models

In [56]:
#these are tunable to achieve max accuracy


Classifiers = {#'LR':LogisticRegression(random_state=42,C=5,max_iter=200),
               'DTC':DecisionTreeClassifier(random_state=42,min_samples_leaf=2),
               #'RF':RandomForestClassifier(random_state=42,n_estimators=100,n_jobs=-1),
               'GBC':GradientBoostingClassifier(random_state=42,n_estimators=400,learning_rate=0.35),
               #'SGD':SGDClassifier(loss="hinge", penalty="l2"),
               #'SVM':svm.SVC(kernel='linear', C=0.10),
               #'NB':MultinomialNB(alpha=.05)
}

In [57]:
#Pipeline to reuse the code
def ML_Pipeline(clf_name):
    clf = Classifiers[clf_name]
    fit = clf.fit(train_features,train['Deal'])
    pred = clf.predict(test_features)
    Accuracy = accuracy_score(test['Deal'],pred)
    Confusion_matrix = confusion_matrix(test['Deal'],pred)
    print('==='*20)
    print('Accuracy = '+str(Accuracy))
    print('==='*20) 
    print(Confusion_matrix)

# # ML Code in Individual Blocks

In [47]:
ML_Pipeline('DTC')

Accuracy = 0.5519125683060109
[[23 38]
 [44 78]]


In [49]:
ML_Pipeline('GBC')

Accuracy = 0.5355191256830601
[[21 40]
 [45 77]]
